export enum DomainErrorCode {
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  INVALID_GAME = 'INVALID_GAME',
  INVALID_GAME_STATE = 'INVALID_GAME_STATE',
  GAME_ALREADY_SUBMITTED = 'GAME_ALREADY_SUBMITTED',
  INVALID_GAME_RESULT = 'INVALID_GAME_RESULT',
  PHOTO_REQUIRED = 'PHOTO_REQUIRED',
  UPLOAD_INVALID = 'UPLOAD_INVALID',
  NOT_ALL_GAMES_COMPLETED = 'NOT_ALL_GAMES_COMPLETED',
  STARPRINT_ALREADY_GENERATED = 'STARPRINT_ALREADY_GENERATED',
  STARPRINT_NOT_FOUND = 'STARPRINT_NOT_FOUND',
  CONSENT_INVALID = 'CONSENT_INVALID'
}
